### ISSUE TITLE
Don't override widths if using overrides in a template

### ISSUE THREAD

**Issue by cdowdy** [cdowdy/boltbetterthumbs#2]
if a width is set in a config:  

````yaml  
srcset:
# other settings  
  modifications:
    small: { 'w': 340 }
    medium: { 'w': 680 }
    large: { 'w': 800 }
    xlarge: { 'w': 1260 }  
````  

and we try to "add" some modifications in a template (for instance changing image format) like so:  

```twig 
{{ img(record.image, 'srcset', {  
    'modifications': { 'medium': { 'fm': 'png'   } }
} ) }}
````  

then the srcset string is invalid. the width for "medium" setting gets overriden to  null.  

```html  
<img src="fallback src img" 
  srcset="<!-- other srcset candidates --> 
        /img/file-name.jpg?fm=png&s=fa230fddc843fa4b1c763b6e72d496f5 0w, <!-- bad width descriptor and no width --> 
        /img/file-name.jpg?w=1260&fit=stretch&s=79f74dc3a92976699cee74ded5b327a5 1400w" 
    alt=""  
````

This ins't the intended behavior nor is it very helpful :) haha.
