### ISSUE TITLE
Allow images to be lazy loaded

### ISSUE THREAD

**Issue by cdowdy** [cdowdy/boltbetterthumbs#28]
Right now if you wanted to lazy load an image you can only use lazy load plugins or scripts that work by a single data attribute or by a class.

This is rigid. Since we use responsive images by default it makes sense to allow by default the markup pattern used by [lazysizes](https://github.com/aFarkas/lazysizes)

To make it flexible and allow other lazy load plugins make a config section with lazyload data/setup.

The default settings for this block should contain a few things. 

  1. Ask if they want to lazyload images. bool
  2. if they want to use lazysizes. if set to true, check for the pattern (in the 2nd list item)
  3. the lazysizes pattern you want to use  
      * [simple pattern](https://github.com/aFarkas/lazysizes#simple-pattern)
      * [combined pattern](https://github.com/aFarkas/lazysizes#combine-data-srcset-with-data-src)
      * [low quality image placeholder](https://github.com/aFarkas/lazysizes#lqipblurry-image-placeholderblur-up-image-technique)
      * [modern transparent srcset pattern](https://github.com/aFarkas/lazysizes#modern-transparent-srcset-pattern)  
  4. if lazyload is true and lazysizes is false then maybe just output the srcset and src attributes. This will take some reworking and I don't want to tackle this yet. 
  

ie:  

```yaml  
# other settings
lazyload_settings: &lazySettings
  lazyLoad_imgs: true
  lazySizes: true
  pattern: lqip #low quality image placeholder  

# custom solution:
lazyload_settings: &lazySettings
  lazyLoad_imgs: true
  lazySizes: false
```

Then in a named config block have use yaml's repeated nodes

```yaml
namedConfigBlock:  
  lazyload: 
    <<: *lazySettings
```

There's just to many variables and lazy load scripts to cover all of them. So either only allow lazysizes right now, or allow lazysizes, rework the config sections and add an option that just spits out the srcset and src attributes to be used in the twig template similar too:  

```twig  
<img sizes="your sizes"  
    srcset="{{ record.image|bthumbSrcset }}" 
   src="{{ record.image|bthumbSrc }}"  >
````  

If i follow that pattern I have to name the filter ( the ``|bthumbSrcset`` portion ) something unique. Using just ``srcset`` or ``src`` is so generic and the actual names I can't guarantee they wont collide with another extensions filters. Using this pattern also allows me to simplify the lazyload section. This will allow me to only care about the lazysizes script and markup patterns. ie:  

```yaml  
# other settings
lazyload_settings: &lazySettings
  lazySizes: true
  pattern: lqip #low quality image placeholder  


# further down in a named config block
namedConfigBlock:  
  lazyload:  
    <<: *lazySettings  
  modifications:  
    # mods  
```

This will use the lazy sizes markup pattern defined in the pattern section and if lazysizes is set to true will load the script from my vendor directory. If its false then the end user can load it from a cdn or their script bundles. 

I think I'll try out this last pattern using filters :)
