### ISSUE TITLE
Choose Fallback Image Size

### ISSUE THREAD

**Issue by saltpeanuts** [cdowdy/boltbetterthumbs#41]
Is it possible to choose the size of the image used as fallback for browsers without srcset support?

For a site with more users on ie11 than non-supporting mobile browsers it would make sense to serve the original image as fallback instead of a smaller one. Otherwise ie11 users can end up with a heavily pixelated scaled-up image.

Looked through the docs but nothing jumps out as a simple way to do it (would prefer to avoid polyfills if possible).

**Comment by cdowdy** [comment]
as of right now no. I assumed (and it seems wrongly so now haha) that if you were supporting older browsers that picturefill (or similar) would be used so i used the "middle" of the modifications for the src candidate to balance it out for size of the download.  

If I can find some time I'll try to put a check if someone wants to use the original then use that are the src candidate... or just use the original image all the time for the src - which would probably be best that way you don't have to do a lot of extra config work!

**Comment by cdowdy** [comment]
This is gonna take a bit, if at all, and I'm not sure how to solve it right now without adding a lot of config setup and checks. Which if it comes to that I'd rather not.  

If  someone were to watermark their images then the src candidate image wouldn't be watermarked. The same for each and every other modification that would be used. IE. watermarks, adjustments (Brightness, Contrast, Gamma Correction, Sharpness), Image Effects (blur, pixelate, filters), background colors, borders or changing the image format. 

The quickest way to use this in your scenario then would be to use the ``{{ srcset(record.image, 'configName }}`` in combo with the ``{{ bthumb( record.image, 'singleImageConfig') }}`` tag and create a single image config block. which kinda stinks haha:  

```twig  
<img sizes="100vw" 
    {{ srcset(record.image, 'configName ' ) }}  
    src="{{ bthumb( record.image, 'singleImageConfig') }}" 
    alt=" your alt text" />
```  

or 

```twig  
<img size="your sizes if using w descriptor"  
  {{ srcset(record.image, 'configName }}  
 src="/files/path/to/your/image.jpg"
  alt=" your alt text" />
```  

as it is right now a config similiar to:

```yaml  
example:
  widthDensity: 'w'
  sizes: [ '100vw'  ]
  use_original: 800
  modifications:
    small:
      w: 200
      fit: 'crop'
    medium:
      w: 350
      fit: 'crop'
    large:
      w: 800
      fit: 'stretch'
    xlarge:
      w: 1400
      fit: 'stretch'
```  

The ``src=`` would be the 800px width image found in large or in the case of the supplied 'betterthumbs' config using the presets that ship with the extension:  

```yaml  
presets: &presets
  small:
    w: 175
    fit: stretch
  medium:
    w: 350
    fit: stretch
  large:
    w: 700
    fit: stretch
  xlarge:
    w: 1400
    fit: stretch  

betterthumbs:
  save_data: true
  altText: 'this is alt'
  widthDensity: 'w'
  sizes: [ '100vw' ]
  modifications:
     <<: *presets
```  

would give you a ``src`` of 700px.
