### ISSUE TITLE
Missing Sizes attribute fallsback to config name

### ISSUE THREAD

**Issue by cdowdy** [cdowdy/boltbetterthumbs#42]
a config with a missing sizes attribute doesn't fallback to the default of 100vw. It fallsback to the named config.  

Example:  
```yaml  
waterMarkedIMG:
  widthDensity: 'w'
  modifications:
    small:
      w: 200
      fit: 'crop'
      mark: 'bthumb-watermark.png'
      markw: '30w'
      markpos: center
    medium:
      w: 350
      fit: 'crop'
      mark: 'bthumb-watermark.png'
      markw: '30w'
      markpos: center
    large:
      w: 500
      fit: 'stretch'
      mark: 'watermark.png'
      markw: '30w'
      markpos: center
    1_large:
      w: 650
      fit: 'stretch'
      mark: 'watermark.png'
      markw: '30w'
      markpos: center
```

produces:

```html  
<img sizes="waterMarkedIMG"
     srcset="srcset candidates"
     src="src candidate"
     alt="alt text provided">
```
