### ISSUE TITLE
Twig cannot be used in record edit/creation page

### ISSUE THREAD

**Issue by cdowdy** [cdowdy/boltbetterthumbs#43]
with allow twig set to true in your contentType field the twig tag no longer renders the image but the escaped twig output.  

contentType Setup:  
```yaml  
pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
            allowtwig: true # here alllow twig is set to true!
        template:
            type: templateselect
            filter: '*.twig'
    taxonomy: [ groups ]
    recordsperpage: 100
```  

Using it in content:  
![betterthumbs-twig-in-content](https://user-images.githubusercontent.com/5969974/27794429-2a2d8668-5fd0-11e7-8dba-43511e2ec2b8.png)  

Result:  
![betterthumbs-twig-escaped-result](https://user-images.githubusercontent.com/5969974/27794437-32104334-5fd0-11e7-8c08-d42f238b3f07.png)
